### ISSUE TITLE
Mainteners

### ISSUE THREAD

**Issue by hekike** [hekike/adyen-node#6]
Hi @evenisse @seb0zz ,

I'm not using `adyen` actively anymore and this is an old codebase from me.
I would be very happy to invite you as maintainers for this project because I see this is important for you.

Before that would do some clean up like: add documentation, consistent style guide, etc.
_(I already updated npm packages and TravisCI config)_

What do you think? Could you help in this project?

**Comment by evenisse** [comment]
Hi Peter,

I'm adding adyen into my project so I will continue to add some features in
this module.
It will be more easy to participate as maintainer.

Emmanuel

**Comment by onchainguy-btc** [comment]
Yes why not. I am going to use this npm package for a few projects in the next month so I am really interested to keep it as clean as possible :+1:

**Comment by hekike** [comment]
@evenisse @seb0zz great! ;)

I'll do the clean up during the weekend and invite you after that.

**Comment by evenisse** [comment]
ping

**Comment by evenisse** [comment]
Hello, I need to patch this module. Can you add me as maintainer?

**Comment by hekike** [comment]
@evenisse @seb0zz sorry for the delay, done, let me know when you need `npm publish`.
